// Copyright © 2025, Ivan Kinder

#pragma once

#include "NativeGameplayTags.h"

namespace P17::Tags
{
	/// @par Input tags
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Axe)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Axe)

	/// @par Player tags.
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe)
	PROJECT17_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe)
}
